# Generated by Django 4.1 on 2022-09-03 10:33

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Beside_db',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('room_name', models.CharField(max_length=110)),
                ('disp_name', models.CharField(max_length=100)),
                ('co2_calib', models.FloatField()),
                ('map_x', models.FloatField()),
                ('map_y', models.FloatField()),
            ],
        ),
        migrations.CreateModel(
            name='Manager_db',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('cycle', models.IntegerField()),
            ],
        ),
        migrations.CreateModel(
            name='Openweather_db',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('api_key', models.CharField(max_length=100)),
                ('location', models.CharField(max_length=100)),
                ('url_init', models.CharField(max_length=200)),
                ('url_meas', models.CharField(max_length=200)),
            ],
        ),
    ]
